import { createFileRoute } from "@tanstack/react-router";
import { CataloguePage, type CatalogueItem } from "@/components/catalogue-page";
export const Route = createFileRoute("/destinations")({ component: DestinationsPage });
const items: CatalogueItem[] = [
  { image: "/muséé12.webp", fr: { title: "Libreville", description: "La capitale et son patrimoine culturel.", label: "Capitale", details: "Libreville combine infrastructures d'affaires, vie culturelle, restauration et accès direct au littoral." }, en: { title: "Libreville", description: "The capital and its cultural heritage.", label: "Capital", details: "Libreville combines business infrastructure, cultural life, dining and direct access to the coast." } },
  { image: "/port-gentil11.webp", fr: { title: "Port-Gentil", description: "Le cœur économique du littoral.", label: "Business", details: "Ville portuaire dynamique, Port-Gentil est idéale pour les séjours professionnels et les rencontres sectorielles." }, en: { title: "Port-Gentil", description: "The economic heart of the coast.", label: "Business", details: "This dynamic port city is ideal for business stays and sector-specific meetings." } },
  { image: "/PLAteau.jpg", fr: { title: "Loango", description: "Une nature sauvage remarquable.", label: "Nature", details: "Le parc de Loango invite à une immersion rare entre forêt, lagune, plage et observation de la faune." }, en: { title: "Loango", description: "Remarkable wilderness.", label: "Nature", details: "Loango National Park offers a rare immersion among forest, lagoon, beach and wildlife." } },
  { image: "/tortue.jpg", fr: { title: "Pongara", description: "Mangroves et plages préservées.", label: "Littoral", details: "Une destination propice aux activités nature, à la détente et à la découverte des écosystèmes côtiers." }, en: { title: "Pongara", description: "Preserved mangroves and beaches.", label: "Coast", details: "A destination for nature activities, relaxation and discovery of coastal ecosystems." } },
  { image: "/plage.jpg", fr: { title: "Pointe Denis", description: "Une escapade marine proche de Libreville.", label: "Incentive", details: "Accessible depuis la capitale, Pointe Denis offre une parenthèse balnéaire parfaite pour les équipes." }, en: { title: "Pointe Denis", description: "A seaside escape near Libreville.", label: "Incentive", details: "Accessible from the capital, Pointe Denis provides an ideal beach retreat for teams." } },
  { image: "/pateaubateké.jpg", fr: { title: "Plateaux Batéké", description: "Des paysages d'exception à explorer.", label: "Aventure", details: "Des reliefs et vastes horizons pour construire une expérience incentive différente et mémorable." }, en: { title: "Bateke Plateaux", description: "Exceptional landscapes to explore.", label: "Adventure", details: "Wide horizons and distinctive landscapes for a different, memorable incentive experience." } },
];
function DestinationsPage() { return <CataloguePage title={{ fr: "Destinations", en: "Destinations" }} intro={{ fr: "Découvrez les villes, les parcs et le littoral gabonais pour enrichir chaque événement.", en: "Discover Gabon's cities, parks and coast to enrich every event." }} items={items} />; }
