import { createFileRoute } from "@tanstack/react-router";
import { CataloguePage, type CatalogueItem } from "@/components/catalogue-page";
export const Route = createFileRoute("/experiences")({ component: ExperiencesPage });
const items: CatalogueItem[] = [
  { image: "/elephant.webp", fr: { title: "Safari à Loango", description: "Observer la faune dans son habitat naturel.", label: "Nature", details: "Une expérience guidée au contact d'une biodiversité exceptionnelle, pensée pour les petits groupes et les programmes incentive." }, en: { title: "Loango Safari", description: "Observe wildlife in its natural habitat.", label: "Nature", details: "A guided experience among exceptional biodiversity, designed for small groups and incentive programmes." } },
  { image: "/tortue6.jpg", fr: { title: "Baie de Pongara", description: "Un littoral préservé pour les équipes.", label: "Littoral", details: "Entre plages, mangroves et faune marine, la baie propose un cadre différent pour renforcer la cohésion." }, en: { title: "Pongara Bay", description: "A preserved coastline for teams.", label: "Coast", details: "Between beaches, mangroves and marine wildlife, the bay offers a distinctive setting for team building." } },
  { image: "/MBIGOU3.jpg", fr: { title: "Patrimoine gabonais", description: "Rencontrer les traditions et les savoir-faire.", label: "Culture", details: "Des rencontres culturelles qui donnent du sens au séjour et favorisent une découverte respectueuse du pays." }, en: { title: "Gabonese Heritage", description: "Meet traditions and craftsmanship.", label: "Culture", details: "Cultural encounters that give meaning to a stay and encourage respectful discovery of the country." } },
  { image: "/chute5.jpg", fr: { title: "Cascades", description: "Une parenthèse spectaculaire au vert.", label: "Aventure", details: "Des excursions au cœur des paysages gabonais, à intégrer dans un programme d'incentive sur mesure." }, en: { title: "Waterfalls", description: "A spectacular escape into nature.", label: "Adventure", details: "Excursions through Gabon's landscapes, ready to be included in a tailored incentive programme." } },
  { image: "/beau.jpg", fr: { title: "Forêt équatoriale", description: "Une immersion dans la biodiversité.", label: "Nature", details: "Des parcours accompagnés pour découvrir les écosystèmes forestiers et leur richesse." }, en: { title: "Equatorial Forest", description: "An immersion in biodiversity.", label: "Nature", details: "Guided journeys to discover forest ecosystems and their remarkable richness." } },
  { image: "/pcouchésoleilcover.jpg", fr: { title: "Détente côtière", description: "Des moments privilégiés au bord de l'eau.", label: "Bien-être", details: "Une pause apaisante entre deux temps forts professionnels, face aux paysages de l'Atlantique." }, en: { title: "Coastal Relaxation", description: "Privileged moments by the water.", label: "Well-being", details: "A calming break between business highlights, overlooking Atlantic landscapes." } },
  { image: "/DETTENT.jpg", fr: { title: "Détente côtière", description: "Des moments privilégiés au bord de l'eau.", label: "Bien-être", details: "Une pause apaisante entre deux temps forts professionnels, face aux paysages de l'Atlantique." }, en: { title: "Coastal Relaxation", description: "Privileged moments by the water.", label: "Well-being", details: "A calming break between business highlights, overlooking Atlantic landscapes." } },
];
function ExperiencesPage() { return <CataloguePage title={{ fr: "Expériences", en: "Experiences" }} intro={{ fr: "Des activités incentive qui combinent découverte, conservation et esprit d'équipe.", en: "Incentive activities combining discovery, conservation and team spirit." }} items={items} />; }
