import { createFileRoute } from "@tanstack/react-router";
import { CataloguePage, type CatalogueItem } from "@/components/catalogue-page";
export const Route = createFileRoute("/investir")({ component: InvestPage });
const items: CatalogueItem[] = [
  { image: "/BaiesdesRois.webp", fr: { title: "Stabilité & sécurité", description: "Un cadre propice aux projets internationaux.", label: "Atout 01", details: "Le Gabon offre un environnement favorable au développement de projets touristiques et événementiels structurés." }, en: { title: "Stability & Security", description: "A framework suited to international projects.", label: "Asset 01", details: "Gabon offers an environment conducive to developing structured tourism and event projects." } },
  { image: "/riverLoge.jpg", fr: { title: "Excellence environnementale", description: "Un territoire engagé pour la conservation.", label: "Atout 02", details: "La conservation de la biodiversité constitue un pilier différenciant pour les partenaires et organisateurs." }, en: { title: "Environmental Excellence", description: "A country committed to conservation.", label: "Asset 02", details: "Biodiversity conservation is a differentiating pillar for partners and event organisers." } },
  { image: "/AFAIRES.webp", fr: { title: "Connectivité", description: "Des infrastructures au service des échanges.", label: "Atout 03", details: "Les infrastructures de transport et de télécommunication soutiennent l'organisation d'événements internationaux." }, en: { title: "Connectivity", description: "Infrastructure supporting exchange.", label: "Asset 03", details: "Transport and telecommunications infrastructure supports the organisation of international events." } },
];
function InvestPage() { return <CataloguePage title={{ fr: "Investir au Gabon", en: "Invest in Gabon" }} intro={{ fr: "Les atouts du Gabon pour les investisseurs, organisateurs et partenaires du tourisme d'affaires.", en: "Gabon's strengths for investors, organisers and business tourism partners." }} items={items} />; }
