import { createFileRoute } from "@tanstack/react-router";
import { CataloguePage, type CatalogueItem } from "@/components/catalogue-page";
export const Route = createFileRoute("/lieux")({ component: VenuesPage });
const items: CatalogueItem[] = [
  { image: "/AFAIRES.webp", fr: { title: "Espace des affaires d'Angondjé", description: "Une plateforme premium pour les grands rendez-vous.", label: "Libreville", details: "Pensé pour les congrès, conférences et salons, cet espace bénéficie d'un emplacement stratégique et d'une offre de services adaptée aux organisateurs internationaux." }, en: { title: "Angondjé Business Hub", description: "A premium platform for major events.", label: "Libreville", details: "Designed for congresses, conferences and trade shows, this venue has a strategic location and services suited to international organisers." } },
  { image: "/riverLoge.jpg", fr: { title: "River Lodge", description: "Un format confidentiel au bord de la lagune.", label: "Pointe Denis", details: "Un lieu intimiste pour les comités exécutifs et retraites d'équipe, avec un environnement naturel propice à la concentration." }, en: { title: "River Lodge", description: "An intimate setting by the lagoon.", label: "Pointe Denis", details: "An intimate venue for executive committees and team retreats, set in a natural environment designed for focus." } },
  { image: "/sogara.webp", fr: { title: "Sogara", description: "Un pôle stratégique de Port-Gentil.", label: "Port-Gentil", details: "Cette destination s'adresse aux rencontres liées à l'industrie, à l'énergie et à la logistique dans la capitale économique." }, en: { title: "Sogara", description: "A strategic hub in Port-Gentil.", label: "Port-Gentil", details: "This destination is ideal for meetings related to industry, energy and logistics in Gabon's economic capital." } },
  { image: "/PalaisCongrèslbv.webp", fr: { title: "Palais des Congrès", description: "Des espaces institutionnels au cœur de Libreville.", label: "Libreville", details: "Des capacités adaptées aux grands rassemblements, cérémonies et rencontres institutionnelles." }, en: { title: "Congress Palace", description: "Institutional event spaces in central Libreville.", label: "Libreville", details: "Capacity suited to major gatherings, ceremonies and institutional meetings." } },
  { image: "/lemeridien.jpg", fr: { title: "Le Méridien", description: "Hébergement et réunion face à l'Atlantique.", label: "Pointe Denis", details: "Un cadre hôtelier confortable associant hébergement, restauration et espaces de réunion pour les délégations." }, en: { title: "Le Méridien", description: "Accommodation and meetings facing the Atlantic.", label: "Pointe Denis", details: "A comfortable hotel setting combining accommodation, dining and meeting space for delegations." } },
  { image: "/BaiesdesRois.webp", fr: { title: "Baie des Rois", description: "Un quartier d'affaires tourné vers le littoral.", label: "Libreville", details: "Une adresse contemporaine pour imaginer des événements urbains, entre affaires, hospitalité et ouverture sur la baie." }, en: { title: "Baie des Rois", description: "A business district opening onto the waterfront.", label: "Libreville", details: "A contemporary address for urban events where business, hospitality and the bay meet." } },
];
function VenuesPage() { return <CataloguePage title={{ fr: "Lieux d'événements", en: "Event venues" }} intro={{ fr: "Sélectionnez un cadre adapté à vos congrès, séminaires et programmes incentive.", en: "Choose a setting suited to your congresses, seminars and incentive programmes." }} items={items} />; }
